<a href="https://colab.research.google.com/github/Maryvictor/numpy_womakerscode/blob/main/Aula_de_Numpy_WomakersCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importar biblioteca
import numpy as np

# **Definições**

**Listas** são estruturas mutáveis, o que significa que seus elementos podem ser alterados ou removidos. Por exemplo, podemos criar uma lista de números e, em seguida, alterar um dos números ou remover um deles.

**Arrays** também são estruturas mutáveis, mas são otimizados para operações com índices. Por exemplo, podemos acessar um elemento de um array usando seu índice, o que é mais rápido do que acessar um elemento de uma lista usando sua posição.

**Tuplas** são estruturas imutáveis, o que significa que seus elementos não podem ser alterados ou removidos. Por exemplo, uma tupla pode ser usada para armazenar um conjunto de dados que não precisa ser alterado, como os dados de um registro de banco de dados.

In [4]:
#declaração de uma lista

l = [4, 8, 2, 12, 5, 8, 0]

In [5]:
#a lista é transformada em Array
arr = np.array(l)
arr

array([ 4,  8,  2, 12,  5,  8,  0])

In [7]:
#Outras formas de se inicializar um Array através do numpy do zero
#np.zeros()
#np.arange()
#np.random.random

In [11]:
#Inicializa uma matriz com numeros zeros, o primeiro número é de linhas, e o segundo colunas.

np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
list(range(0,3))

[0, 1, 2]

In [21]:
#esse metodo funciona como o de cima, mas em numpy
array_range = np.arange(1,11)
array_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
type(array_range)

numpy.ndarray

In [24]:
np.random.random((3,3))

array([[0.58369251, 0.96709048, 0.56814786],
       [0.78880404, 0.03204055, 0.22074365],
       [0.69665449, 0.31398707, 0.31973323]])

# Atividades

1 - Crie um array com 4 linhas e 3 colunas com valores aleatórios

In [27]:
array1 = np.random.random((4, 3))
array1

array([[0.15899619, 0.2878026 , 0.09177522],
       [0.21473336, 0.8986678 , 0.54527464],
       [0.37132697, 0.00579054, 0.21522526],
       [0.07509154, 0.41983745, 0.96500237]])

2 - Crie um array com 5 colunas e 10 linhas inicializados com zeros

In [28]:
array2 = np.zeros((10, 5))
array2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3 - Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatórios




In [32]:
array3 = np.random.randint(0, 100, (3, 5))
array3

array([[12, 25, 36, 80, 91],
       [31, 75, 92, 97, 27],
       [91, 97, 53, 13, 96]])

# Por que usar numpy e não listas?

* Arrays NumPy aceita que todos os elementos sejam de
diferentes tipo de dados, contudo o array sempre terá
apenas um tipo de dados. Contudo a normal dentro da
análise de dados que **usamos apenas um tipo de dados
dentro de um array**.

* Um único tipo de dados também resulta em arrays NumPy
ocupando **menos espaço na memória** em comparação
com listas.

* Quando precisamos de uma **estrutura multidimensional**
para armazenar os dados, optamos por arrays em vez de
listas, pois as listas podem ser unidimensionais apenas.

* Se precisarmos de um comprimento fixo e alocação
estática, usamos arrays em vez de listas.

* Quando é necessária uma processamento de dados mais
rápido, preferimos arrays em vez de listas.

* Tipos de dados primitivos podem ser armazenados
diretamente em arrays, mas não em listas.

In [35]:
#array 3D

arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
arr3_2d = np.array([[9, 2], [3, 4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

In [36]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [37]:
arr = np.zeros((2,4))
arr


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
#Retorna a forma do Array, onde temos 2 linhas e 4 colunas, shape é forma em inglês

arr.shape

(2, 4)

In [40]:
#primeira dimensão é a linha, e segunda dimensão a coluna em array de 2 dimensões
#flatter(acentador), coloca o array em apenas uma dimensão, pega o conjunto das linhas e transforma num só

In [42]:
#temos o reshaping tb, ele redimensiona no formato que voce deseja
arr = np.array([[3, 4,2], [8, 11, 5]])
arr.reshape((3,2))

array([[ 3,  4],
       [ 2,  8],
       [11,  5]])

In [50]:
arr = np.zeros((2, 3, 4)) # 2 matrizes, 3 linhas, 4 colunas

In [51]:
arr = arr.flatten()
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

# Atividades

1 - Reduza o array (5,7) a apenas uma dimensão

In [52]:
arr1 = np.zeros((5,7))
arr1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [53]:
arr1 = arr1.flatten()
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

2 - Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. Os numeros da sua cartela variam entre 1 e 30, e voce terá 10 participipantes. Cada cartela terá 12 numeros (4, 3).

Crie um array que represente esse jogo.

In [57]:
bingo = np.random.randint(1, 31, (10, 4, 3))
bingo

array([[[20, 30,  1],
        [19,  3, 14],
        [10,  3, 13],
        [10, 26, 15]],

       [[15, 25,  7],
        [ 2,  9, 20],
        [11, 27, 26],
        [15, 19, 11]],

       [[13, 12,  4],
        [ 7, 18,  5],
        [ 5,  4, 16],
        [ 7, 11,  5]],

       [[ 9, 15, 19],
        [16,  9,  6],
        [27,  5, 28],
        [17, 17,  2]],

       [[14, 18, 22],
        [ 9, 15,  5],
        [ 8, 12,  5],
        [25, 18, 23]],

       [[29, 20, 29],
        [14, 13, 13],
        [ 2, 27,  4],
        [25, 22,  7]],

       [[ 9,  9, 27],
        [25, 30,  4],
        [ 2,  3, 10],
        [25,  5, 11]],

       [[15,  2, 30],
        [ 6,  4, 20],
        [30, 13,  4],
        [ 3, 28, 19]],

       [[30, 25, 21],
        [29,  5,  4],
        [19,  7,  2],
        [21, 18, 17]],

       [[10, 23,  9],
        [23, 17, 15],
        [21, 12, 30],
        [19, 20, 25]]])

3 - Faça o reshape das suas cartela para que haja 5 cartelas de 4 linhas e 6 colunas

In [58]:
bingo = bingo.reshape((5, 4, 6 ))
bingo

array([[[20, 30,  1, 19,  3, 14],
        [10,  3, 13, 10, 26, 15],
        [15, 25,  7,  2,  9, 20],
        [11, 27, 26, 15, 19, 11]],

       [[13, 12,  4,  7, 18,  5],
        [ 5,  4, 16,  7, 11,  5],
        [ 9, 15, 19, 16,  9,  6],
        [27,  5, 28, 17, 17,  2]],

       [[14, 18, 22,  9, 15,  5],
        [ 8, 12,  5, 25, 18, 23],
        [29, 20, 29, 14, 13, 13],
        [ 2, 27,  4, 25, 22,  7]],

       [[ 9,  9, 27, 25, 30,  4],
        [ 2,  3, 10, 25,  5, 11],
        [15,  2, 30,  6,  4, 20],
        [30, 13,  4,  3, 28, 19]],

       [[30, 25, 21, 29,  5,  4],
        [19,  7,  2, 21, 18, 17],
        [10, 23,  9, 23, 17, 15],
        [21, 12, 30, 19, 20, 25]]])

In [59]:
np.array([0.9, 8.7, 6.5]).dtype

dtype('float64')

In [60]:
np.array([1, 6, 60, 43]).dtype

dtype('int64')

In [63]:
np.array(['Maria', 'Paulo', 'Vertigem']).dtype

dtype('<U8')

In [69]:
arr = np.array([0.76, 8.74, 6.53]).dtype
arr


dtype('float64')

In [70]:
#Dtype com argumento
arr = np.array([0.76, 8.74, 6.53], dtype=np.float32)
arr

array([0.76, 8.74, 6.53], dtype=float32)

In [72]:
#conversão, transforma True e False em 0 e 1
arr = np.array([[True, False], [True, True]], dtype=np.bool8)
arr


array([[ True, False],
       [ True,  True]])

In [73]:
arr.astype(np.int32)

array([[1, 0],
       [1, 1]], dtype=int32)

In [74]:
#coerção, nesse caso viram todos strings
np.array(['Pedra', False, 0, 98.76])

array(['Pedra', 'False', '0', '98.76'], dtype='<U32')

In [75]:
#hierarquia de coerção
#Adicionar um float a um array de int mudará todo os valores para float.

np.array([1, 4, 4]).dtype


dtype('int64')

In [79]:
x = np.array([1, 4, 4])
x[1]

4

In [80]:
x = np.array([1, 4, 4, 4.5])
x[1]


4.0

In [76]:
np.array([1, 4, 4, 3.3]).dtype


dtype('float64')

In [77]:
#Adicionar um inteiro em um array de booleanos transformará todo o array em inteiros
np.array([True, False]).dtype

dtype('bool')

In [78]:
np.array([True, False, 3]).dtype

dtype('int64')